name: CI-CD

on:
  push:
    branches: ["develop", "master"]
    
jobs:
  CI:
    runs-on: ubuntu:latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: sijomc/sonarscan-action@1.1
      - name: Construção da imagem docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            Fabricio1805/auth-login:v1
            Fabricio1805/auth-login:latest
          

  
    
