name: auth-login

on:
    push:
        branches: [master, develop, qa]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '21'
            - name: Build project
              run: mvn clean install -DskipTests
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
            - name: Build docker image
              run: docker build -t fabricio1905/auth-login:${{ github.run_number }} .
            - name: Push image docker
              run: docker push fabricio1905/auth-login:${{ github.run_number }}

    #deploy:
    #    needs: build
    #    runs-on: self-hosted
    #    steps:
    #        - name: Pull image from docker hub
    #          run: docker pull fabricio1905/auth-login:latest
    #        - name: Remove docker container
    #          run: docker rm -f auth-login
    #        - name: Run docker container
    #          run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} --name deploy_ghactions danieleleaoe/deploy_ghactions
