name: CI-CD

on:
  push:
    branches: ["master" , "develop"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      #- name: Run SonarQube Scan
      # uses: sijomc/sonarscan-action@1.1

      - name: Docker Hub Authentication
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .  # Contexto agora é o diretório raiz
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricio1905/auth-login:${{ github.run_number }}
            fabricio1905/auth-login:latest
