name: CI-CD

on:
  push:
    branches: ["master"]
    
jobs:
  CI:
    runs-on: ubuntu:latest

    steps: 
      - name: checkout do codigo
        uses: actions/checkout@v4.2.2

      - name: sonar
        uses: sijomc/sonarscan-action@1.1
      
      - name: authenticação no docker hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERHUB_USER}} 
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        
      - name: Construção da imagem docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            Fabricio1805/auth-login:${{github.run_number}}
            Fabricio1805/auth-login:latest
          

  
    
